### PR TITLE
setuptools is required for installed software as well

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by nschloe** [comment]
Really? How? It's never used anywhere in pipdate itself.

**Comment by hmaarrfk** [comment]
Hmm, let me check my logs then.

**Comment by hmaarrfk** [comment]
https://github.com/nschloe/pipdate/blob/master/pipdate/main.py#L9

**Comment by hmaarrfk** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=147892&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=578

**Comment by nschloe** [comment]
Fair enough. I'd always assumed that `pkg_resources` is distributed with the standard library!

https://stackoverflow.com/a/10538412/353337

**Comment by nschloe** [comment]
Thanks again, just released 0.5.1.

**Comment by hmaarrfk** [comment]
it probably is, and I probably wouldn't have open an "issue" but you have it listed as a build requirement.

So i figured you had already decided to be explicit about it.

**Pull request merged**
